### ISSUE TITLE
Filters: Combine queries (<, <=, >, >=) filter on different fields

### ISSUE THREAD

**Issue by jaberbu** [jaberbu/onfirework#19]
Now you have to make two queries and combine them
```
import * as _ from 'lodash';

const date_1 = await Onfirework.listDocs([['DATE_START', '>=', date]]);
const date_2 = await Onfirework.listDocs([['DATE_END', '<=', date]]);

const date = _.intersectionWith(date_1, date_2, _.isEqual);
```
The idea is that this combination is done directly in Onfirework function, abstracting the user and minify [Query limitations](https://firebase.google.com/docs/firestore/query-data/queries#query_limitations)

```
const date = await Onfirework.listDocs([ ['DATE_START', '>=', date], ['DATE_END', '<=', date] ]);
```

**Comment by ezequieltejada** [comment]
😯

**Comment by ezequieltejada** [comment]
Should this be done on the same Onfirework.listDocs method?
